### ISSUE TITLE
[FEATURE] Add timer at get sucess rate button

### ISSUE THREAD

**Issue by leocodeio** [leocodeio/Cropto#11]
1. user should not be able to spam the get success rate button, add a timer in place 
2. f you are not comfortable with the codebase try doing it in react
3. this is the component in the project in which the sucess rate button exists
![image](https://github.com/user-attachments/assets/c8e57942-bd38-46ee-bf84-b6b3ea0f7fdb)
![image](https://github.com/user-attachments/assets/ae73fc47-1b7e-4f85-8798-f95939a6dfaa)

**Comment by Utkarsh-2005** [comment]
Please assign me this issue

**Comment by leocodeio** [comment]
@Utkarsh-2005 , reach out on any queries

**Comment by Utkarsh-2005** [comment]
Hey @leocodeio, in your data.server.tsx, you are defining the getPesticidesFunction function, where it is fetching from "{process.env.ML_MODEL_URL}/pesticides". But no such path seems to be defined in the fastapi server. Is the code not updated?

**Comment by leocodeio** [comment]
@Utkarsh-2005 ,  the ml modle url will be your locally running fastapi server endpoint
![image](https://github.com/user-attachments/assets/309c0f2d-7491-4d39-b913-18ddba53c128)
these are the commands that will help you do this
![image](https://github.com/user-attachments/assets/469dfa31-7ebf-40f5-af68-df633c175fb7)
feel free to reach out if this does not work

**Comment by Utkarsh-2005** [comment]
I have configured the api and connected it, I am asking where is the /pesticides route defined in the api, I am getting an error in the frontend, I believe it's because of that route not being present

**Comment by leocodeio** [comment]
@Utkarsh-2005 -- thanks for pointing out I have updated the main branch sync and try now

**Comment by leocodeio** [comment]
@Utkarsh-2005 stay connected man, there are other issues too if you want to work check out my repos
